name: Release Build
on:
  push:
    branches:
      - '**'
jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            preset_prefix: linux
          - os: windows-latest
            preset_prefix: windows
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set preset name
        id: preset
        shell: bash
        run: |
          if [ "${{ matrix.build_type }}" == "Debug" ]; then
            echo "name=${{ matrix.preset_prefix }}-debug" >> $GITHUB_OUTPUT
          else
            echo "name=${{ matrix.preset_prefix }}-release" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list https://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
          sudo apt-get update
          sudo apt-get install -y ninja-build clang vulkan-sdk shaderc
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja -y
          choco install llvm -y
          
          # Install Vulkan SDK
          $VulkanVersion = "1.4.328.1"
          $Installer = "VulkanSDK-$VulkanVersion-Installer.exe"
          $DownloadURL = "https://sdk.lunarg.com/sdk/download/$VulkanVersion/windows/$Installer"
          echo "GETTING VULKAN FROM $DownloadURL"

          Invoke-WebRequest -Uri $DownloadURL -OutFile $Installer
          # Start-Process -FilePath $Installer -ArgumentList "/S" -Wait
          Start-Process -FilePath .\$Installer -ArgumentList "--root D:\VulkanSDK --accept-licenses --default-answer --confirm-command install" -Wait


          # Set environment variable for this session
          # echo "VULKAN_SDK=C:\VulkanSDK\$VulkanVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "VULKAN_SDK=D:\VulkanSDK" >> $env:GITHUB_ENV
          echo "D:\VulkanSDK\Bin" >> $env:GITHUB_PATH
      
      - name: Configure CMake
        run: cmake --preset ${{ steps.preset.outputs.name }}
      
      - name: Build
        run: cmake --build build/${{ steps.preset.outputs.name }}