name: Release Build
on:
  push:
    branches:
      - '**'
jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            preset_prefix: linux
          - os: windows-latest
            preset_prefix: windows
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set preset name
        id: preset
        shell: bash
        run: |
          if [ "${{ matrix.build_type }}" == "Debug" ]; then
            echo "name=${{ matrix.preset_prefix }}-debug" >> $GITHUB_OUTPUT
          else
            echo "name=${{ matrix.preset_prefix }}-release" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang libvulkan-dev
      
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja -y
          choco install llvm -y
          
          # Install Vulkan SDK
          $VulkanVersion = "1.3.290.0"
          $Installer = "VulkanSDK-$VulkanVersion-Installer.exe"
          $DownloadURL = "https://sdk.lunarg.com/sdk/download/$VulkanVersion/windows/$Installer"
          echo "GETTING VULKAN FROM $DownloadURL"

          Invoke-WebRequest -Uri $DownloadURL -OutFile $Installer
          Start-Process -FilePath $Installer -ArgumentList "/S" -Wait
          
          # Set environment variable for this session
          echo "VULKAN_SDK=C:\VulkanSDK\$VulkanVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: Configure CMake
        run: cmake --preset ${{ steps.preset.outputs.name }}
      
      - name: Build
        run: cmake --build build/${{ steps.preset.outputs.name }}